name: device_calendar
description: A cross platform plugin for modifying calendars on the user's device.
version: 4.3.2
homepage: https://github.com/builttoroam/device_calendar/tree/master

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  sprintf: ^7.0.0
  timezone: ^0.9.0
  flutter_native_timezone:
    git:
      ref: a9669f7e84fb704dc85dc7c88f771f36d52bf318
      url: git@github.com:curefit/flutter_native_timezone.git
      path: .

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.builttoroam.devicecalendar
        pluginClass: DeviceCalendarPlugin
      ios:
        pluginClass: DeviceCalendarPlugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13"
